Refactor Jenkinsfile-CD for improved readability
Signed-off-by: somisettyvasanthkumar <somisettyvasanthkumar@gmail.com>

diff --git a/Jenkinsfile-CD b/Jenkinsfile-CD
--- a/Jenkinsfile-CD
+++ b/Jenkinsfile-CD
@@ -3,17 +3,11 @@ pipeline {
     agent any
 
     parameters {
-
         string(
-
             name: 'IMAGE_TAG',
-
             defaultValue: '',
-
             description: 'Docker Image Tag'
-
         )
-
     }
 
     stages {
@@ -23,11 +17,8 @@ pipeline {
             steps {
 
                 input(
-
                     message: "Deploy Docker Image ${params.IMAGE_TAG} to EC2?",
-
                     ok: "Deploy"
-
                 )
 
             }
@@ -53,12 +44,24 @@ pipeline {
                                     execCommand: """
 
                                     docker pull somisettyvasanth/petclinic:${params.IMAGE_TAG}
+
+                                    docker stop petclinic || true
+
+                                    docker rm petclinic || true
+
                                     docker run -d \
                                     --name petclinic \
+                                    --restart unless-stopped \
                                     -p 8080:8080 \
                                     somisettyvasanth/petclinic:${params.IMAGE_TAG}
+
+                                    sleep 20
+
                                     docker ps
-                                    curl http://localhost:8080
+
+                                    docker logs --tail 30 petclinic
+
+                                    curl -f http://localhost:8080
 
                                     """
 
@@ -81,15 +84,11 @@ pipeline {
     post {
 
         success {
-
-            echo "Application Successfully Deployed"
-
+            echo 'Application Successfully Deployed'
         }
 
         failure {
-
-            echo "Deployment Failed"
-
+            echo 'Deployment Failed'
         }
 
     }
